pg:
  host: ep-floral-haze-264573.eu-central-1.aws.neon.tech
  name: projectatest
  user: HeadcrabJ
  pass: oGSQsaW1y9id
redis:
  host: redis-12549.c300.eu-central-1-1.ec2.cloud.redislabs.com:12549
  pass: 61cDJVPE90GEJCb4OobNF6WDEsX7xsbK
auth:
  secret_key: MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCUvzAskrRPKscEUcfLvbl95I2pWyDJ5b/iiL/Bo0OtYwzvkekNsJyBK41VLFAYUhrliH7ybuRwDZKA9lgnJaiDb3IOGricGM0Ts0FmdFGaAJhOVeA4a5/57HDtt0io5pI22HcG8+4EnMIPQ9u3Nn85Ra/LT/ClPbdaQEgSSBEvHwIDAQAB
server:
  port: 8000
